name: transact_pay_sdk
description: "TransactPay Flutter Package provide innovative and flexible European BIN sponsorship and modular payment, debit, and prepaid services."
version: 0.0.1
homepage: https://github.com/fussion-integrator/transact_pay_sdk
repository: https://github.com/fussion-integrator/transact_pay_sdk

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.3.0
  intl: ^0.19.0
  transact_pay: ^0.0.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/footer.png


